title: Neurons and Notations
author:
    name: Sricharan Sunder
    email: sricharan.iisc@gmail.com
    github: sricharan92
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
permalink: /blog/:year/:month/:day/:title
plugins:
    - jekyll-feed
    - jekyll-include-cache 
